const Gears = [
  {
    id: 151,
    item: "Porter Bag",
    description:
      "A hiking bag backpack with multiple compartments, compression straps, and padded shoulder straps to help you carry the load more efficiently.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/porterbag.jpg",
    cost: 6000,
    discount: 0,
  },
  {
    id: 152,
    item: "Safari Boots",
    description:
      "Specialized footwear designed for hiking and other outdoor activities in wet and rainy conditions.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/boots.jpg",
    cost: 5500,
    discount: 500,
  },
  {
    id: 153,
    item: "Sleeping Bag",
    description:
      "A lightweight, portable and insulated bag designed to keep you warm and comfortable while sleeping outdoors. ",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/sleepingbag.jpg",
    cost: 7000,
    discount: 500,
  },
  {
    id: 154,
    item: "Woolen Socks",
    description:
      "Specialized socks designed for hiking and other outdoor activities in wet and cold conditions.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/woolensocks.jpg",
    cost: 500,
    discount: 0,
  },
  {
    id: 155,
    item: "Headlight",
    description:
      "Portable and hands-free lighting lamp. Ideal for navigation in low light conditions or at night.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/headlight.jpg",
    cost: 2500,
    discount: 0,
  },
  {
    id: 156,
    item: "Gaiters",
    description:
      "Protective coverings worn over hiking boots and pants for additional protection against rocks, debris, water, and snow. ",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/gaiters.jpg",
    cost: 4500,
    discount: 500,
  },
  {
    id: 157,
    item: "Hiking T-Shirt",
    description:
      "Moisturized synthetic T-shirts designed for outdoor activities like hiking, trekking and camping",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/tshirt.jpg",
    cost: 5000,
    discount: 500,
  },
  {
    id: 158,
    item: "Jacket",
    description:
      "Puffed hiking jackets are insulated jackets that provide you warmth and insulation without weighing you down",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/jacket.jpg",
    cost: 3000,
    discount: 500,
  },
  {
    id: 159,
    item: "Water Bottle",
    description:
      "Stainless Thermos Lightweight Wide-Mouth Vacuum Water Bottle - 32 fl. oz",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/stainlessthermos.jpg",
    cost: 2000,
    discount: 500,
  },
  {
    id: 160,
    item: "Hydration Bag",
    description:
      "Hydration backpack designed to hold a water bladder / reservoir with a drinking tube for easy access to water while hiking.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/hydrationbag.jpg",
    cost: 4000,
    discount: 500,
  },
  {
    id: 161,
    item: "Summit Pants",
    description:
      "Specialized pants for mountaineering and other high-altitude activities. They provide warmth, protection from the elements, and ease of movement while climbing.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/summitpants.jpg",
    cost: 1500,
    discount: 500,
  },
  {
    id: 162,
    item: "Wind Jacket",
    description:
      "Protects you from wind while allowing your body to breathe and regulate temperature.Ideal for outdoor activities like hiking, camping, and climbing.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/windjacket.jpg",
    cost: 6000,
    discount: 500,
  },
  {
    id: 163,
    item: "Thermal T-shirt",
    description:
      "Provides insulation and warmth during cold weather. Made of fabric that traps air between its fibers, creating a layer of insulation that helps retain body heat.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/thermaltshirt.jpg",
    cost: 1500,
    discount: 200,
  },
  {
    id: 164,
    item: "Thermal Bottom Pants",
    description:
      "Provides insulation and warmth during cold weather. Made of fabric that traps air between its fibers, creating a layer of insulation that helps retain body heat.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/thermalbottom.jpg",
    cost: 2600,
    discount: 300,
  },
  {
    id: 165,
    item: "Fleece Jacket",
    description:
      "Outerwear lightweight wool like fabrics, breathable, and warm, Popular choice for outdoor activities in cool to cold weather.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/fleecejacket.jpg",
    cost: 4590,
    discount: 400,
  },
  {
    id: 166,
    item: "Rain Jacket - Poncho",
    description:
      "Designed to protect you from the rain or wind. Made from a waterproof material (nylon or polyester) that helps keep you dry.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/ponchos.jpg",
    cost: 3000,
    discount: 500,
  },
  {
    id: 167,
    item: "Sandles",
    description:
      "Designed to provide comfort, support, and protection while allowing your feet to breathe and stay cool in warm weather.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/sandles.jpg",
    cost: 3000,
    discount: 500,
  },

  {
    id: 169,
    item: "Sneakers",
    description:
      " Footwear designed for outdoor activities, such as hiking, walking, and running. Suitable for rugged terrain and outdoor environments. ",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/sneakers.jpg",
    cost: 3000,
    discount: 500,
  },

  {
    id: 171,
    item: "Hiking Pole",
    description:
      "Trekking pole, designed to assist hikers and walkers while trekking on trails or off-road terrain",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/hikingpole.jpg",
    cost: 3000,
    discount: 500,
  },
  {
    id: 172,
    item: "Moisture-Wicking Underwear",
    description:
      "Garments made from breathable, moisture-wicking fabrics that help to keep you dry and comfortable during physical activity.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/moistureunderwear.jpg",
    cost: 3000,
    discount: 500,
  },
  {
    id: 173,
    item: "Gloves",
    description:
      "Outdoor gloves designed to protect your hands while hiking and other outdoor activities.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/gloves.jpg",
    cost: 3000,
    discount: 500,
  },
  {
    id: 174,
    item: "Cap",
    description:
      "Headgear designed for outdoor activities,  Provides protection from the sun and other weather elements.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/cap.jpg",
    cost: 3000,
    discount: 500,
  },
  {
    id: 175,
    item: "Hat",
    description:
      "Headgear designed for outdoor activities,  Provides protection from the sun and other weather elements.",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/hat.jpg",
    cost: 3000,
    discount: 500,
  },
  {
    id: 176,
    item: "Balaclava",
    description:
      "Headgear that covers the head, neck, and face, leaving only a small opening for the eyes, nose, and mouth. ",
    size: "1",
    weight: "1",
    availability: "instock",
    src: "/images/gears/balaclava.jpg",
    cost: 3000,
    discount: 500,
  },
];

export const getGearData = () => {
  return Gears;
};
