const Hikes = [
  {
    id: 152,
    location: "Mount Kipiriri",
    title: "Mount Kipiriri",
    cost: 3000,
    date: "10th June 2023",
    maxLatitude: "3459",
    difficulty: "Modarate",
    distance: "18 Km",
    src: "/images/mountkipipiri.jpg",
    card: "A",
    duration: "5-6 hours",
  },

  {
    id: 153,
    location: "Mount  Kinangop",
    title: "Mount  Kinangop",
    cost: 3000,
    date: "8th  July 2023",
    maxLatitude: "3363",
    difficulty: "Moderate",
    distance: "17.5 Km",
    src: "/images/mountkinangop.jpeg",
    card: "B",
    duration: "6-8 hours",
  },
  {
    id: 154,
    location: "Mount Kenya",
    title: "Mount Kenya",
    cost: 3000,
    date: "16th - 20th August 2023",
    maxLatitude: "3500",
    difficulty: "Challenge",
    distance: "13 Km",
    src: "/images/mountkenya.jpeg",
    card: "A",
    duration: "6-8 hours",
  },
  {
    id: 155,
    location: "Elephant Hill",
    title: "Elephant Hill",
    cost: 3000,
    date: "7th October 2023",
    maxLatitude: "2900",
    difficulty: "Ultimate Challenge",
    distance: "39 Km",
    src: "/images/elephanthill.webp",
    card: "B",
    duration: "6-8 hours",
  },
  {
    id: 156,
    location: "Rurimeria ->Table Mountain Traverse",
    title: "Rurimeria ->Table Mountain Traverse",
    cost: 3000,
    date: "4th November 2023",
    maxLatitude: "2900",
    difficulty: "Ultimate Challenge",
    distance: "39 Km",
    src: "/images/rurimeria.jpeg",
    card: "B",
    duration: "6-8 hours",
  },
  {
    id: 157,
    location: "Table Mountain Gilgil",
    title: "Table Mountain Gilgil",
    cost: 3000,
    date: "2nd December 2023",
    maxLatitude: "2900",
    difficulty: "Ultimate Challenge",
    distance: "39 Km",
    src: "/images/tablemountain.webp",
    card: "B",
    duration: "6-8 hours",
  },
];

export default Hikes;
